module Full_adder_tb;
  logic a, b, c;
  wire y1, y2;
  
  Full_adder dut(.a(a), .b(b), .c(c), .y1(y1), .y2(y2));
  
  initial begin
    
    $dumpfile("Full_adder.vcd");
    $dumpvars;

    
    a = 0; b = 0; c = 0; #10;
    a = 0; b = 0; c = 1; #10;
    a = 0; b = 1; c = 0; #10;
    a = 0; b = 1; c = 1; #10;
    a = 1; b = 0; c = 0; #10;
    a = 1; b = 0; c = 1; #10;
    a = 1; b = 1; c = 0; #10;
    a = 1; b = 1; c = 1; #10;
    
    $finish;
    
  end
endmodule
